version: '3.8'
services:
  app:
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - clot_usercreate_service_default
    depends_on:
      - clot_usercreate_service-db-1

networks:
  clot_usercreate_service_default:
    external: true
